- name: install grafana in redhat server
  hosts: redhat
  become: true
  vars:
    grafana_version: 9.5.1
    grafana_package: grafana-{{ grafana_version }}-1.x86_64.rpm
    grafana_package_url: https://dl.grafana.com/oss/release/{{ grafana_package }}
    grafana_gpg_key_url: https://grafanarel.s3.amazonaws.com/RPM-GPG-KEY-grafana
  tasks:
    - name: Remove Grafana Enterprise
      yum:
        name: grafana-enterprise
        state: absent
    - name: Import Grafana GPG key
      rpm_key:
        key: "{{ grafana_gpg_key_url }}"
        state: present
    - name: Download Grafana package
      get_url:
        url: "{{ grafana_package_url }}"
        dest: /tmp/{{ grafana_package }}
    - name: Verify Grafana package signature
      command: rpm --import "{{ grafana_gpg_key_url }}"
      changed_when: false
      ignore_errors: true
    - name: Install Grafana
      yum:
        name: /tmp/{{ grafana_package }}
        state: present
        disable_gpg_check: yes
    - name: Start Grafana
      systemd:
        name: grafana-server
        state: started
        enabled: yes
    - name: Configure Grafana
      lineinfile:
        path: /etc/grafana/grafana.ini
        regexp: '{{ item.regexp }}'
        line: '{{ item.line }}'
      with_items:
        - { regexp: '^http_port = .*', line: 'http_port = 3000' }
        - { regexp: '^;domain = .*', line: 'domain = {{ ansible_fqdn }}' }
    - name: Restart grafana-server
      service:
        name: grafana-server
        state: restarted

