- name: Install Grafana from .tar.gz file
  hosts: grafana
  become: true

  vars:
    grafana_version: 8.1.5
    grafana_download_url: "https://dl.grafana.com/oss/release/grafana-{{ grafana_version }}.linux-amd64.tar.gz"
    grafana_install_dir: /opt/grafana

  tasks:
    - name: Install required packages
      package:
        name: [tar, gzip]
        state: present

    - name: Create Grafana installation directory
      file:
        path: "{{ grafana_install_dir }}"
        state: directory
        owner: grafana
        group: grafana
        mode: '0755'

    - name: Download Grafana .tar.gz file
      get_url:
        url: "{{ grafana_download_url }}"
        dest: /tmp/grafana.tar.gz
        mode: '0644'

    - name: Extract Grafana .tar.gz file
      become: true
      unarchive:
        src: /tmp/grafana.tar.gz
        dest: "{{ grafana_install_dir }}"
        remote_src: yes
        creates: "{{ grafana_install_dir }}/grafana-{{ grafana_version }}"

    - name: Set ownership and permissions on Grafana directory
      file:
        path: "{{ grafana_install_dir }}"
        owner: grafana
        group: grafana
        mode: '0755'
        recurse: yes

    - name: Start and enable Grafana service
      systemd:
        name: grafana-server
        state: started
        enabled: yes

